LOGIN_URL = "https://lotw.arrl.org/lotwuser/default"  # noqa
WAS_PAGE_URL = "https://lotw.arrl.org/lotwuser/awardaccount?awardaccountcmd=status&awg_id=WAS&ac_acct=1"  # noqa
WAZ_PAGE_URL = "https://lotw.arrl.org/lotwuser/awardaccount?awardaccountcmd=status&awg_id=WAZ&ac_acct=1"  # noqa
DXCC_PAGE_URL = "https://lotw.arrl.org/lotwuser/awardaccount?awardaccountcmd=status&awg_id=DXCC&ac_acct=1"  # noqa
VUCC_PAGE_URL = "https://lotw.arrl.org/lotwuser/awardaccount?awardaccountcmd=status&awg_id=VUCC&ac_acct=1"  # noqa
WPX_PAGE_URL = "https://lotw.arrl.org/lotwuser/awardaccount?awardaccountcmd=status&awg_id=WPX&ac_acct=1"  # noqa
TRIPLE_PAGE_URL = "https://lotw.arrl.org/lotwuser/accountcredits?awg_id=WAS&ac_acct=1&aw_id=WAS-TRIPLE"  # noqa
QSLS_PAGE_URL = "https://lotw.arrl.org/lotwuser/qsos?qso_query=1&awg_id=DXCC&ac_acct=1&qso_callsign=&qso_owncall=&qso_startdate=&qso_starttime=&qso_enddate=&qso_endtime=&qso_mode=&qso_band=&qso_qsl=yes&qso_dxcc=&qso_sort=QSL+Date&qso_descend=yes&acct_sel=DXCC%3B1"  # noqa
DETAILS_PAGE_URL = "https://lotw.arrl.org/lotwuser/qsodetail?qso="  # noqa
FIND_PAGE_URL = "https://lotw.arrl.org/lotwuser/act"  # noqa
ACCOUNT_CREDITS_URL = "https://lotw.arrl.org/lotwuser/accountcredits?"  # noqa
